// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using SNHub.Jobs.Infrastructure.Persistence;
#nullable disable
namespace SNHub.Jobs.Infrastructure.Persistence.Migrations;
[DbContext(typeof(JobsDbContext))]
partial class JobsDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "10.0.0").HasAnnotation("Relational:MaxIdentifierLength", 63);
        Npgsql.EntityFrameworkCore.PostgreSQL.Metadata.NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);
        modelBuilder.Entity("SNHub.Jobs.Domain.Entities.Job", b =>
        {
            b.Property<Guid>("Id").HasColumnName("id").HasColumnType("uuid");
            b.Property<Guid>("EmployerId").HasColumnName("employer_id").HasColumnType("uuid");
            b.Property<string>("Title").IsRequired().HasMaxLength(200).HasColumnName("title").HasColumnType("character varying(200)");
            b.Property<string>("Description").IsRequired().HasColumnName("description").HasColumnType("text");
            b.Property<int>("Status").HasColumnName("status").HasColumnType("integer");
            b.Property<DateTimeOffset>("CreatedAt").HasColumnName("created_at").HasColumnType("timestamptz");
            b.Property<DateTimeOffset>("UpdatedAt").HasColumnName("updated_at").HasColumnType("timestamptz");
            b.HasKey("Id");
            b.ToTable("jobs", "jobs");
        });
#pragma warning restore 612, 618
    }
}
