// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using SNHub.JobEnhancer.Infrastructure.Persistence;

#nullable disable

namespace SNHub.JobEnhancer.Infrastructure.Persistence.Migrations;

[DbContext(typeof(JobEnhancerDbContext))]
partial class JobEnhancerDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder b)
    {
#pragma warning disable 612, 618
        b.HasAnnotation("ProductVersion", "9.0.3")
         .HasAnnotation("Relational:MaxIdentifierLength", 63);
        b.UseIdentityByDefaultColumns();

        b.Entity("SNHub.JobEnhancer.Domain.Entities.EnhancementResult", e =>
        {
            e.Property<Guid>("Id").HasColumnName("id").HasColumnType("uuid");
            e.Property<Guid>("JobId").IsRequired().HasColumnName("job_id").HasColumnType("uuid");
            e.Property<Guid>("RequestedBy").IsRequired().HasColumnName("requested_by").HasColumnType("uuid");
            e.Property<int>("Status").HasColumnName("status").HasColumnType("integer");
            e.Property<string>("ErrorMessage").HasMaxLength(2000).HasColumnName("error_message");
            e.Property<string>("OriginalTitle").IsRequired().HasMaxLength(200).HasColumnName("original_title");
            e.Property<string>("OriginalDescription").IsRequired().HasColumnName("original_description");
            e.Property<string>("OriginalRequirements").HasColumnName("original_requirements");
            e.Property<string>("EnhancedTitle").HasMaxLength(200).HasColumnName("enhanced_title");
            e.Property<string>("EnhancedDescription").HasColumnName("enhanced_description");
            e.Property<string>("EnhancedRequirements").HasColumnName("enhanced_requirements");
            e.Property<int>("ScoreBefore").HasDefaultValue(0).HasColumnName("score_before");
            e.Property<int>("ScoreAfter").HasDefaultValue(0).HasColumnName("score_after");
            e.Property<string>("BiasIssuesJson").HasDefaultValue("[]").HasColumnType("jsonb").HasColumnName("bias_issues_json");
            e.Property<string>("MissingFieldsJson").HasDefaultValue("[]").HasColumnType("jsonb").HasColumnName("missing_fields_json");
            e.Property<string>("ImprovementsJson").HasDefaultValue("[]").HasColumnType("jsonb").HasColumnName("improvements_json");
            e.Property<string>("SuggestedSkillsJson").HasDefaultValue("[]").HasColumnType("jsonb").HasColumnName("suggested_skills_json");
            e.Property<bool>("IsAccepted").HasDefaultValue(false).HasColumnName("is_accepted");
            e.Property<DateTimeOffset?>("AcceptedAt").HasColumnType("timestamptz").HasColumnName("accepted_at");
            e.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamptz").HasColumnName("created_at");
            e.Property<DateTimeOffset>("UpdatedAt").HasColumnType("timestamptz").HasColumnName("updated_at");
            e.HasKey("Id");
            e.HasIndex("JobId").HasDatabaseName("ix_enhancement_results_job_id");
            e.HasIndex("RequestedBy").HasDatabaseName("ix_enhancement_results_requested_by");
            e.HasIndex("CreatedAt").HasDatabaseName("ix_enhancement_results_created_at");
            e.ToTable("enhancement_results", "enhancer");
        });
#pragma warning restore 612, 618
    }
}
