// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using SNHub.Matching.Infrastructure.Persistence;

#nullable disable

namespace SNHub.Matching.Infrastructure.Persistence.Migrations;

[DbContext(typeof(MatchingDbContext))]
partial class MatchingDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder b)
    {
#pragma warning disable 612, 618
        b.HasAnnotation("ProductVersion", "9.0.3")
         .HasAnnotation("Relational:MaxIdentifierLength", 63);
        b.UseIdentityByDefaultColumns();

        b.Entity("SNHub.Matching.Domain.Entities.EmbeddingRecord", e =>
        {
            e.Property<Guid>("Id").HasColumnName("id").HasColumnType("uuid");
            e.Property<Guid>("DocumentId").IsRequired().HasColumnName("document_id").HasColumnType("uuid");
            e.Property<int>("DocumentType").HasColumnName("document_type").HasColumnType("integer");
            e.Property<int>("Status").HasColumnName("status").HasColumnType("integer");
            e.Property<string>("ErrorMessage").HasMaxLength(2000).HasColumnName("error_message").HasColumnType("character varying(2000)");
            e.Property<int>("RetryCount").HasDefaultValue(0).HasColumnName("retry_count").HasColumnType("integer");
            e.Property<DateTimeOffset?>("LastIndexedAt").HasColumnName("last_indexed_at").HasColumnType("timestamptz");
            e.Property<DateTimeOffset>("CreatedAt").HasColumnName("created_at").HasColumnType("timestamptz");
            e.Property<DateTimeOffset>("UpdatedAt").HasColumnName("updated_at").HasColumnType("timestamptz");
            e.HasKey("Id");
            e.HasIndex(new[] { "DocumentId", "DocumentType" }).IsUnique().HasDatabaseName("ix_embedding_records_document");
            e.HasIndex("Status").HasDatabaseName("ix_embedding_records_status");
            e.HasIndex("UpdatedAt").HasDatabaseName("ix_embedding_records_updated_at");
            e.ToTable("embedding_records", "matching");
        });
#pragma warning restore 612, 618
    }
}
