// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using SNHub.Notifications.Infrastructure.Persistence;
#nullable disable
namespace SNHub.Notifications.Infrastructure.Persistence.Migrations;
[DbContext(typeof(NotificationsDbContext))]
partial class NotificationsDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion","10.0.0").HasAnnotation("Relational:MaxIdentifierLength",63);
        Npgsql.EntityFrameworkCore.PostgreSQL.Metadata.NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);
        modelBuilder.Entity("SNHub.Notifications.Domain.Entities.Notification", b =>
        {
            b.Property<Guid>("Id").HasColumnName("id"); b.Property<Guid>("UserId").HasColumnName("user_id");
            b.Property<int>("Type").HasColumnName("type"); b.Property<string>("Title").IsRequired().HasMaxLength(200).HasColumnName("title");
            b.Property<string>("Message").IsRequired().HasMaxLength(1000).HasColumnName("message");
            b.Property<string>("ActionUrl").HasMaxLength(2048).HasColumnName("action_url");
            b.Property<string>("MetadataJson").HasColumnType("jsonb").HasColumnName("metadata");
            b.Property<bool>("IsRead").HasDefaultValue(false).HasColumnName("is_read");
            b.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamptz").HasColumnName("created_at");
            b.Property<DateTimeOffset?>("ReadAt").HasColumnType("timestamptz").HasColumnName("read_at");
            b.HasKey("Id"); b.HasIndex(new[]{"UserId","IsRead"}).HasDatabaseName("ix_notifications_user_read");
            b.ToTable("notifications","notifications");
        });
#pragma warning restore 612, 618
    }
}
