// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using SNHub.Profiles.Infrastructure.Persistence;
#nullable disable
namespace SNHub.Profiles.Infrastructure.Persistence.Migrations;
[DbContext(typeof(ProfilesDbContext))]
partial class ProfilesDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion","10.0.0").HasAnnotation("Relational:MaxIdentifierLength",63);
        Npgsql.EntityFrameworkCore.PostgreSQL.Metadata.NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);
        modelBuilder.Entity("SNHub.Profiles.Domain.Entities.CandidateProfile", b =>
        {
            b.Property<Guid>("Id").HasColumnName("id"); b.Property<Guid>("UserId").HasColumnName("user_id");
            b.Property<string>("Headline").HasMaxLength(200).HasColumnName("headline");
            b.Property<string>("Bio").HasMaxLength(3000).HasColumnName("bio");
            b.Property<int>("ExperienceLevel").HasColumnName("experience_level");
            b.Property<int>("YearsOfExperience").HasDefaultValue(0).HasColumnName("years_of_experience");
            b.Property<int>("Availability").HasColumnName("availability");
            b.Property<string>("SkillsJson").IsRequired().HasColumnType("jsonb").HasDefaultValue("[]").HasColumnName("skills");
            b.Property<string>("CertificationsJson").IsRequired().HasColumnType("jsonb").HasDefaultValue("[]").HasColumnName("certifications");
            b.Property<string>("ServiceNowVersionsJson").IsRequired().HasColumnType("jsonb").HasDefaultValue("[]").HasColumnName("servicenow_versions");
            b.Property<int>("ProfileCompleteness").HasDefaultValue(0).HasColumnName("profile_completeness");
            b.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamptz").HasColumnName("created_at");
            b.Property<DateTimeOffset>("UpdatedAt").HasColumnType("timestamptz").HasColumnName("updated_at");
            b.HasKey("Id"); b.HasIndex("UserId").IsUnique().HasDatabaseName("ix_candidate_profiles_user");
            b.ToTable("candidate_profiles","profiles");
        });
        modelBuilder.Entity("SNHub.Profiles.Domain.Entities.EmployerProfile", b =>
        {
            b.Property<Guid>("Id").HasColumnName("id"); b.Property<Guid>("UserId").HasColumnName("user_id");
            b.Property<string>("CompanyName").HasMaxLength(200).HasColumnName("company_name");
            b.Property<bool>("IsVerified").HasDefaultValue(false).HasColumnName("is_verified");
            b.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamptz").HasColumnName("created_at");
            b.Property<DateTimeOffset>("UpdatedAt").HasColumnType("timestamptz").HasColumnName("updated_at");
            b.HasKey("Id"); b.HasIndex("UserId").IsUnique().HasDatabaseName("ix_employer_profiles_user");
            b.ToTable("employer_profiles","profiles");
        });
#pragma warning restore 612, 618
    }
}
