// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using SNHub.Applications.Infrastructure.Persistence;

#nullable disable

namespace SNHub.Applications.Infrastructure.Persistence.Migrations;

[DbContext(typeof(ApplicationsDbContext))]
partial class ApplicationsDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "9.0.3").HasAnnotation("Relational:MaxIdentifierLength", 63);
        modelBuilder.UseIdentityByDefaultColumns();
        modelBuilder.Entity("SNHub.Applications.Domain.Entities.JobApplication", b =>
        {
            b.Property<Guid>("Id").HasColumnName("id");
            b.Property<Guid>("JobId").HasColumnName("job_id");
            b.Property<Guid>("CandidateId").HasColumnName("candidate_id");
            b.Property<int>("Status").HasDefaultValue(1).HasColumnName("status");
            b.Property<string>("CoverLetter").HasMaxLength(5000).HasColumnName("cover_letter");
            b.Property<string>("CvUrl").HasMaxLength(2048).HasColumnName("cv_url");
            b.Property<string>("EmployerNotes").HasMaxLength(2000).HasColumnName("employer_notes");
            b.Property<string>("RejectionReason").HasMaxLength(1000).HasColumnName("rejection_reason");
            b.Property<DateTimeOffset>("AppliedAt").HasColumnType("timestamptz").HasColumnName("applied_at");
            b.Property<DateTimeOffset>("UpdatedAt").HasColumnType("timestamptz").HasColumnName("updated_at");
            b.Property<DateTimeOffset?>("StatusChangedAt").HasColumnType("timestamptz").HasColumnName("status_changed_at");
            b.HasKey("Id");
            b.HasIndex(new[] { "JobId", "CandidateId" }).IsUnique().HasDatabaseName("ix_applications_job_candidate");
            b.ToTable("applications", "applications");
        });
#pragma warning restore 612, 618
    }
}
