// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using SNHub.CvParser.Infrastructure.Persistence;

#nullable disable

namespace SNHub.CvParser.Infrastructure.Persistence.Migrations;

[DbContext(typeof(CvParserDbContext))]
partial class CvParserDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder b)
    {
#pragma warning disable 612, 618
        b.HasAnnotation("ProductVersion", "9.0.3")
         .HasAnnotation("Relational:MaxIdentifierLength", 63);
        b.UseIdentityByDefaultColumns();

        b.Entity("SNHub.CvParser.Domain.Entities.CvParseResult", e =>
        {
            e.Property<Guid>("Id").HasColumnName("id").HasColumnType("uuid");
            e.Property<Guid>("UserId").IsRequired().HasColumnName("user_id").HasColumnType("uuid");
            e.Property<string>("BlobPath").IsRequired().HasMaxLength(1024).HasColumnName("blob_path").HasColumnType("character varying(1024)");
            e.Property<string>("OriginalFileName").IsRequired().HasMaxLength(255).HasColumnName("original_file_name").HasColumnType("character varying(255)");
            e.Property<string>("ContentType").IsRequired().HasMaxLength(100).HasColumnName("content_type").HasColumnType("character varying(100)");
            e.Property<long>("FileSizeBytes").HasColumnName("file_size_bytes").HasColumnType("bigint");
            e.Property<int>("Status").HasColumnName("status").HasColumnType("integer");
            e.Property<string>("ErrorMessage").HasMaxLength(2000).HasColumnName("error_message").HasColumnType("character varying(2000)");
            e.Property<string>("FirstName").HasMaxLength(100).HasColumnName("first_name").HasColumnType("character varying(100)");
            e.Property<string>("LastName").HasMaxLength(100).HasColumnName("last_name").HasColumnType("character varying(100)");
            e.Property<string>("Email").HasMaxLength(320).HasColumnName("email").HasColumnType("character varying(320)");
            e.Property<string>("Phone").HasMaxLength(50).HasColumnName("phone").HasColumnType("character varying(50)");
            e.Property<string>("Location").HasMaxLength(200).HasColumnName("location").HasColumnType("character varying(200)");
            e.Property<string>("Headline").HasMaxLength(200).HasColumnName("headline").HasColumnType("character varying(200)");
            e.Property<string>("Summary").HasMaxLength(2000).HasColumnName("summary").HasColumnType("character varying(2000)");
            e.Property<string>("CurrentRole").HasMaxLength(200).HasColumnName("current_role").HasColumnType("character varying(200)");
            e.Property<int?>("YearsOfExperience").HasColumnName("years_of_experience").HasColumnType("integer");
            e.Property<string>("LinkedInUrl").HasMaxLength(500).HasColumnName("linkedin_url").HasColumnType("character varying(500)");
            e.Property<string>("GitHubUrl").HasMaxLength(500).HasColumnName("github_url").HasColumnType("character varying(500)");
            e.Property<string>("SkillsJson").IsRequired().HasDefaultValue("[]").HasColumnName("skills_json").HasColumnType("jsonb");
            e.Property<string>("CertificationsJson").IsRequired().HasDefaultValue("[]").HasColumnName("certifications_json").HasColumnType("jsonb");
            e.Property<string>("ServiceNowVersionsJson").IsRequired().HasDefaultValue("[]").HasColumnName("servicenow_versions_json").HasColumnType("jsonb");
            e.Property<int>("OverallConfidence").HasDefaultValue(0).HasColumnName("overall_confidence").HasColumnType("integer");
            e.Property<string>("FieldConfidencesJson").IsRequired().HasDefaultValue("{}").HasColumnName("field_confidences_json").HasColumnType("jsonb");
            e.Property<bool>("IsApplied").HasDefaultValue(false).HasColumnName("is_applied").HasColumnType("boolean");
            e.Property<DateTimeOffset?>("AppliedAt").HasColumnName("applied_at").HasColumnType("timestamptz");
            e.Property<DateTimeOffset>("CreatedAt").HasColumnName("created_at").HasColumnType("timestamptz");
            e.Property<DateTimeOffset>("UpdatedAt").HasColumnName("updated_at").HasColumnType("timestamptz");
            e.HasKey("Id");
            e.HasIndex("UserId").HasDatabaseName("ix_cv_parse_results_user_id");
            e.HasIndex("Status").HasDatabaseName("ix_cv_parse_results_status");
            e.HasIndex("CreatedAt").HasDatabaseName("ix_cv_parse_results_created_at");
            e.ToTable("cv_parse_results", "cvparser");
        });
#pragma warning restore 612, 618
    }
}
