// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using SNHub.Users.Infrastructure.Persistence;

#nullable disable

namespace SNHub.Users.Infrastructure.Persistence.Migrations;

[DbContext(typeof(UsersDbContext))]
partial class UsersDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder b)
    {
#pragma warning disable 612, 618
        b.HasAnnotation("ProductVersion", "9.0.3")
         .HasAnnotation("Relational:MaxIdentifierLength", 63);
        b.UseIdentityByDefaultColumns();

        b.Entity("SNHub.Users.Domain.Entities.UserProfile", e =>
        {
            e.Property<Guid>("Id").HasColumnName("id").HasColumnType("uuid");
            e.Property<Guid>("UserId").IsRequired().HasColumnName("user_id").HasColumnType("uuid");
            e.Property<string>("FirstName").HasMaxLength(100).HasColumnName("first_name").HasColumnType("character varying(100)");
            e.Property<string>("LastName").HasMaxLength(100).HasColumnName("last_name").HasColumnType("character varying(100)");
            e.Property<string>("Email").HasMaxLength(320).HasColumnName("email").HasColumnType("character varying(320)");
            e.Property<string>("PhoneNumber").HasMaxLength(30).HasColumnName("phone_number").HasColumnType("character varying(30)");
            e.Property<string>("Headline").HasMaxLength(200).HasColumnName("headline").HasColumnType("character varying(200)");
            e.Property<string>("Bio").HasMaxLength(2000).HasColumnName("bio").HasColumnType("character varying(2000)");
            e.Property<string>("Location").HasMaxLength(200).HasColumnName("location").HasColumnType("character varying(200)");
            e.Property<string>("ProfilePictureUrl").HasMaxLength(2048).HasColumnName("profile_picture_url").HasColumnType("character varying(2048)");
            e.Property<string>("LinkedInUrl").HasMaxLength(500).HasColumnName("linkedin_url").HasColumnType("character varying(500)");
            e.Property<string>("GitHubUrl").HasMaxLength(500).HasColumnName("github_url").HasColumnType("character varying(500)");
            e.Property<string>("WebsiteUrl").HasMaxLength(500).HasColumnName("website_url").HasColumnType("character varying(500)");
            e.Property<bool>("IsPublic").HasDefaultValue(true).HasColumnName("is_public").HasColumnType("boolean");
            e.Property<int>("YearsOfExperience").HasDefaultValue(0).HasColumnName("years_of_experience").HasColumnType("integer");
            e.Property<string>("Country").HasMaxLength(3).HasColumnName("country").HasColumnType("character varying(3)");
            e.Property<string>("TimeZone").HasMaxLength(100).HasColumnName("time_zone").HasColumnType("character varying(100)");
            e.Property<bool>("IsDeleted").HasDefaultValue(false).HasColumnName("is_deleted").HasColumnType("boolean");
            e.Property<DateTimeOffset?>("DeletedAt").HasColumnName("deleted_at").HasColumnType("timestamptz");
            e.Property<Guid?>("DeletedBy").HasColumnName("deleted_by").HasColumnType("uuid");
            e.Property<DateTimeOffset>("CreatedAt").HasColumnName("created_at").HasColumnType("timestamptz");
            e.Property<DateTimeOffset>("UpdatedAt").HasColumnName("updated_at").HasColumnType("timestamptz");
            e.HasKey("Id");
            e.HasIndex("UserId").IsUnique().HasDatabaseName("ix_user_profiles_user_id");
            e.HasIndex("Email").HasDatabaseName("ix_user_profiles_email");
            e.HasIndex("IsDeleted").HasDatabaseName("ix_user_profiles_is_deleted");
            e.ToTable("user_profiles", "users");
        });
#pragma warning restore 612, 618
    }
}
