// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using SNHub.Users.Infrastructure.Persistence;

#nullable disable

namespace SNHub.Users.Infrastructure.Persistence.Migrations;

[DbContext(typeof(UsersDbContext))]
partial class UsersDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "10.0.0").HasAnnotation("Relational:MaxIdentifierLength", 63);
        Npgsql.EntityFrameworkCore.PostgreSQL.Metadata.NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);
        modelBuilder.Entity("SNHub.Users.Domain.Entities.UserProfile", b =>
        {
            b.Property<Guid>("Id").HasColumnName("id").HasColumnType("uuid");
            b.Property<Guid>("UserId").HasColumnName("user_id").HasColumnType("uuid");
            b.Property<string>("Headline").HasMaxLength(200).HasColumnName("headline").HasColumnType("character varying(200)");
            b.Property<string>("Bio").HasMaxLength(2000).HasColumnName("bio").HasColumnType("character varying(2000)");
            b.Property<string>("Location").HasMaxLength(200).HasColumnName("location").HasColumnType("character varying(200)");
            b.Property<string>("ProfilePictureUrl").HasMaxLength(2048).HasColumnName("profile_picture_url").HasColumnType("character varying(2048)");
            b.Property<string>("CvUrl").HasMaxLength(2048).HasColumnName("cv_url").HasColumnType("character varying(2048)");
            b.Property<string>("LinkedInUrl").HasMaxLength(500).HasColumnName("linkedin_url").HasColumnType("character varying(500)");
            b.Property<string>("GitHubUrl").HasMaxLength(500).HasColumnName("github_url").HasColumnType("character varying(500)");
            b.Property<string>("WebsiteUrl").HasMaxLength(500).HasColumnName("website_url").HasColumnType("character varying(500)");
            b.Property<bool>("IsPublic").HasDefaultValue(true).HasColumnName("is_public").HasColumnType("boolean");
            b.Property<int>("YearsOfExperience").HasDefaultValue(0).HasColumnName("years_of_experience").HasColumnType("integer");
            b.Property<string>("Country").HasMaxLength(3).HasColumnName("country").HasColumnType("character varying(3)");
            b.Property<string>("TimeZone").HasMaxLength(100).HasColumnName("time_zone").HasColumnType("character varying(100)");
            b.Property<DateTimeOffset>("CreatedAt").HasColumnName("created_at").HasColumnType("timestamptz");
            b.Property<DateTimeOffset>("UpdatedAt").HasColumnName("updated_at").HasColumnType("timestamptz");
            b.HasKey("Id");
            b.HasIndex("UserId").IsUnique().HasDatabaseName("ix_user_profiles_user_id");
            b.ToTable("user_profiles", "users");
        });
#pragma warning restore 612, 618
    }
}
